<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.jefersonsantos06</groupId>
    <artifactId>stdnum4j-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>stdnum4j</name>
    <description>A Java library to parse, validate and reformat standard numbers and codes.</description>
    <url>https://github.com/jefersonsantos06/stdnum4j</url>

    <modules>
        <module>stdnum4j-core</module>
        <module>stdnum4j-tck</module>
        <module>stdnum4j-br</module>
        <module>stdnum4j-international</module>
        <module>stdnum4j-eu</module>
        <module>stdnum4j-latam</module>
        <module>stdnum4j-na</module>
        <module>stdnum4j-apac</module>
        <module>stdnum4j-africa</module>
        <module>stdnum4j-postal</module>
        <module>stdnum4j-all</module>
    </modules>

    <properties>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <junit.version>5.11.4</junit.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.github.jefersonsantos06</groupId>
                <artifactId>stdnum4j-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jefersonsantos06</groupId>
                <artifactId>stdnum4j-tck</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jefersonsantos06</groupId>
                <artifactId>stdnum4j-br</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jefersonsantos06</groupId>
                <artifactId>stdnum4j-international</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jefersonsantos06</groupId>
                <artifactId>stdnum4j-eu</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jefersonsantos06</groupId>
                <artifactId>stdnum4j-latam</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jefersonsantos06</groupId>
                <artifactId>stdnum4j-na</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jefersonsantos06</groupId>
                <artifactId>stdnum4j-apac</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jefersonsantos06</groupId>
                <artifactId>stdnum4j-africa</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.jefersonsantos06</groupId>
                <artifactId>stdnum4j-postal</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.13.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.2.5</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.4.1</version>
                    <configuration>
                        <archive>
                            <manifestEntries>
                                <Automatic-Module-Name>${auto.module.name}</Automatic-Module-Name>
                            </manifestEntries>
                        </archive>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
