package io.github.jefersonsantos06.stdnum.eu;

import io.github.jefersonsantos06.stdnum.spi.StdNum;
import io.github.jefersonsantos06.stdnum.spi.StdNumProvider;

import java.util.Collection;
import java.util.List;

/** Registers the European number types with the registry. */
public final class EuProvider implements StdNumProvider {

    @Override
    public Collection<StdNum> numbers() {
        return List.of(
                AdNrt.INSTANCE,
                AlNipt.INSTANCE,
                AtBusinessid.INSTANCE,
                AtUid.INSTANCE,
                AtVnr.INSTANCE,
                AzVoen.INSTANCE,
                BeBis.INSTANCE,
                BeEid.INSTANCE,
                BeNn.INSTANCE,
                BeOgmVcs.INSTANCE,
                BeSsn.INSTANCE,
                BeVat.INSTANCE,
                BgEgn.INSTANCE,
                BgPnf.INSTANCE,
                BgVat.INSTANCE,
                ByUnp.INSTANCE,
                ChEsr.INSTANCE,
                ChSsn.INSTANCE,
                ChUid.INSTANCE,
                ChVat.INSTANCE,
                CyVat.INSTANCE,
                CzDic.INSTANCE,
                CzIco.INSTANCE,
                CzRc.INSTANCE,
                DeHandelsregisternummer.INSTANCE,
                DeIdnr.INSTANCE,
                DeLeitweg.INSTANCE,
                DeStnr.INSTANCE,
                DeVat.INSTANCE,
                DeWkn.INSTANCE,
                DkCpr.INSTANCE,
                DkCvr.INSTANCE,
                EeIk.INSTANCE,
                EeKmkr.INSTANCE,
                EeRegistrikood.INSTANCE,
                EsCcc.INSTANCE,
                EsCif.INSTANCE,
                EsDni.INSTANCE,
                EsNie.INSTANCE,
                EsNif.INSTANCE,
                EsPostalCode.INSTANCE,
                EuAt02.INSTANCE,
                EuEcnumber.INSTANCE,
                EuOss.INSTANCE,
                FiAlv.INSTANCE,
                FiAssociationid.INSTANCE,
                FiHetu.INSTANCE,
                FiVeronumero.INSTANCE,
                FiYtunnus.INSTANCE,
                FoVn.INSTANCE,
                FrNif.INSTANCE,
                FrNir.INSTANCE,
                FrRcs.INSTANCE,
                FrSiren.INSTANCE,
                FrSiret.INSTANCE,
                FrTva.INSTANCE,
                GbNhs.INSTANCE,
                GbUpn.INSTANCE,
                GbUtr.INSTANCE,
                GbVat.INSTANCE,
                GrAmka.INSTANCE,
                GrVat.INSTANCE,
                HrOib.INSTANCE,
                HuAnum.INSTANCE,
                IePps.INSTANCE,
                IeVat.INSTANCE,
                IsKennitala.INSTANCE,
                IsVsk.INSTANCE,
                ItAic.INSTANCE,
                ItCodicefiscale.INSTANCE,
                ItIva.INSTANCE,
                LiPeid.INSTANCE,
                LtAsmens.INSTANCE,
                LtPvm.INSTANCE,
                LuTva.INSTANCE,
                LvPvn.INSTANCE,
                McTva.INSTANCE,
                MdIdno.INSTANCE,
                MePib.INSTANCE,
                MkEdb.INSTANCE,
                MtVat.INSTANCE,
                NlBrin.INSTANCE,
                NlBsn.INSTANCE,
                NlBtw.INSTANCE,
                NlIdentiteitskaartnummer.INSTANCE,
                NlOnderwijsnummer.INSTANCE,
                NlPostcode.INSTANCE,
                NoFodselsnummer.INSTANCE,
                NoKontonr.INSTANCE,
                NoMva.INSTANCE,
                NoOrgnr.INSTANCE,
                PlNip.INSTANCE,
                PlPesel.INSTANCE,
                PlRegon.INSTANCE,
                PtCc.INSTANCE,
                PtNif.INSTANCE,
                RoCf.INSTANCE,
                RoCnp.INSTANCE,
                RoCui.INSTANCE,
                RoOnrc.INSTANCE,
                RsPib.INSTANCE,
                SeOrgnr.INSTANCE,
                SePersonnummer.INSTANCE,
                SePostnummer.INSTANCE,
                SeVat.INSTANCE,
                SiDdv.INSTANCE,
                SiEmso.INSTANCE,
                SiMaticna.INSTANCE,
                SkDph.INSTANCE,
                SkIco.INSTANCE,
                SkRc.INSTANCE,
                SmCoe.INSTANCE,
                UaEdrpou.INSTANCE,
                UaRntrc.INSTANCE);
    }
}
